### ISSUE TITLE
random error found in my logs

### ISSUE THREAD

**Issue by vikktrey123** [JartanFTW/Trade-Notifier#46]
2021-01-28 10:20:28,177:ERROR:Task exception was never retrieved
future: <Task finished name='Task-14' coro=<TradeWorker.check_trade_loop() done, defined at trade_worker.py:38> exception=ConnectError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')>
Traceback (most recent call last):
  File "httpx\_exceptions.py", line 326, in map_exceptions
  File "httpx\_client.py", line 1502, in _send_single_request
  File "httpcore\_async\connection_pool.py", line 218, in arequest
  File "httpcore\_async\connection.py", line 92, in arequest
  File "httpcore\_async\connection.py", line 118, in _open_socket
  File "httpcore\_backends\auto.py", line 44, in open_tcp_stream
  File "httpcore\_backends\asyncio.py", line 243, in open_tcp_stream
  File "contextlib.py", line 135, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "trade_worker.py", line 46, in check_trade_loop
  File "utilities.py", line 169, in get_roli_data
  File "httpx\_client.py", line 1548, in get
  File "httpx\_client.py", line 1371, in request
  File "httpx\_client.py", line 1406, in send
  File "httpx\_client.py", line 1444, in _send_handling_auth
  File "httpx\_client.py", line 1476, in _send_handling_redirects
  File "httpx\_client.py", line 1502, in _send_single_request
  File "contextlib.py", line 135, in __exit__
  File "httpx\_exceptions.py", line 343, in map_exceptions
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

**Comment by JartanFTW** [comment]
This is caused by you never opening roblox.com and/or rolimons.com on whatever device it is you're using.
This isn't a bug in the code.
Please open a web browser and navigate to those two urls. After doing so, you can simply close them and run Horizon, and Horizon should work as intended.
Let me know how that goes.

**Comment by vikktrey123** [comment]
> 
> 
> This is caused by you never opening roblox.com and/or rolimons.com on whatever device it is you're using.
> This isn't a bug in the code.
> Please open a web browser and navigate to those two urls. After doing so, you can simply close them and run Horizon, and Horizon should work as intended.
> Let me know how that goes.

didnt fix it, actually i had both open at once on two different browsers and it still didnt send the webhook nor fix its random stops when a trade is completed

**Comment by JartanFTW** [comment]
Interesting. I'll be sure to look into this.
Can you contact me on Discord so I can send you a testing version?
Jartan#7450

**Comment by JartanFTW** [comment]
With HTTPX we can disable SSL certification on client startup: https://www.python-httpx.org/advanced/#ssl-certificates

This would be an option in the debug section of config, where the user can enable or disable SSL certification.
