### ISSUE TITLE
error log that might have something to do with random stops

### ISSUE THREAD

**Issue by vikktrey123** [JartanFTW/Trade-Notifier#49]
`2021-01-30 18:48:37,337:ERROR:Task exception was never retrieved
future: <Task finished name='Task-14' coro=<TradeWorker.check_trade_loop() done, defined at trade_worker.py:46> exception=ConnectTimeout('')>
Traceback (most recent call last):
  File "httpx\_exceptions.py", line 326, in map_exceptions
  File "httpx\_client.py", line 1502, in _send_single_request
  File "httpcore\_async\connection_pool.py", line 218, in arequest
  File "httpcore\_async\connection.py", line 92, in arequest
  File "httpcore\_async\connection.py", line 118, in _open_socket
  File "httpcore\_backends\auto.py", line 44, in open_tcp_stream
  File "httpcore\_backends\asyncio.py", line 243, in open_tcp_stream
  File "contextlib.py", line 135, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "trade_worker.py", line 50, in check_trade_loop
  File "user.py", line 136, in get_trade_status_info
  File "httpx\_client.py", line 1548, in get
  File "httpx\_client.py", line 1371, in request
  File "httpx\_client.py", line 1406, in send
  File "httpx\_client.py", line 1444, in _send_handling_auth
  File "httpx\_client.py", line 1476, in _send_handling_redirects
  File "httpx\_client.py", line 1502, in _send_single_request
  File "contextlib.py", line 135, in __exit__
  File "httpx\_exceptions.py", line 343, in map_exceptions
httpx.ConnectTimeout
`

**Comment by vikktrey123** [comment]
[01 30 2021 16 58 20.log](https://github.com/JartanFTW/Trade-Notifier/files/5899097/01.30.2021.16.58.20.log)
